name: Docker Image DEV CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker linux
      run: |
        docker build -f Docker/linux-x64/Dockerfile -t fbarresi/softplc:1.2.${{ github.run_number }}-beta-linux .
        docker push fbarresi/softplc:1.2.${{ github.run_number }}-beta-linux 
      working-directory: ./SoftPlc
    - name: Build Docker arm
      run: |
        docker build -f Docker/arm/Dockerfile -t fbarresi/softplc:1.2.${{ github.run_number }}-beta-arm .
        docker push fbarresi/softplc:1.2.${{ github.run_number }}-beta-arm
      working-directory: ./SoftPlc
    - name: Build Docker windows
      run: |
        docker build -f Docker/windows/Dockerfile -t fbarresi/softplc:1.2.${{ github.run_number }}-beta-win .
        docker push fbarresi/softplc:1.2.${{ github.run_number }}-beta-win
      working-directory: ./SoftPlc
    
